### ISSUE TITLE
[Feature] Publish to Kubesphere Appstore  

### ISSUE THREAD

**Issue by everpcpc** [datafuselabs/helm-charts#29]
https://github.com/kubesphere/helm-charts

ref: 
https://kubesphere.io/docs/pluggable-components/app-store/
https://kubesphere.io/docs/workspace-administration/upload-helm-based-application/

**Comment by PsiACE** [comment]
I recently verified our helm charts on KubeSphere and opened a PR https://github.com/kubesphere/helm-charts/pull/260 .
