### ISSUE TITLE
[query] service only select pod 0

### ISSUE THREAD

**Issue by washanhanzi** [datafuselabs/helm-charts#82]
https://github.com/datafuselabs/helm-charts/blob/dcedb74c22254b1f5bf2059174ca6a66519eaf6b/charts/databend-query/templates/service.yaml#L22

this line only let databend-query service select pod 0?

`replicaCount` above 1 make no sense with this selector.

**Comment by everpcpc** [comment]
Yes, that's the intention.

**Comment by washanhanzi** [comment]
> Yes, that's the intention.

I don't get it. Does it mean the helm chart won't support deployment with a query cluster? @everpcpc

**Comment by everpcpc** [comment]
You can increase `replicaCount` to make a cluster deployment. And just query from node 0 would be OK for the cluster.

**Comment by washanhanzi** [comment]
OK. Thanks a lot. I will close the issue.
